### ISSUE TITLE
ImportError while using in pytest

### ISSUE THREAD

**Issue by makhtev** [ethereum/web3.py#3346]
### What happened?

ImportError: cannot import name 'ContractName' from 'eth_typing' (/opt/venv/lib/python3.10/site-packages/eth_typing/__init__.py)

After [this](https://github.com/ethereum/eth-typing/commit/18e27da2d569b5aa1954912339ba4d7d70fc8b1d) commit, old version of web3 not working anymore with pytest.

### Code that produced the error

```python
import web3
import pytest

pytest.console_main()
```

### Full error output

```shell
Traceback (most recent call last):
  File "/usr/local/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 197, in console_main
    code = main()
  File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 155, in main
    config = _prepareconfig(args, plugins)
  File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 337, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/_pytest/helpconfig.py", line 105, in pytest_cmdline_parse
    config = yield
  File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1143, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1492, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1379, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 414, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/usr/local/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/usr/local/lib/python3.10/site-packages/web3/tools/__init__.py", line 1, in <module>
    from .pytest_ethereum import (
  File "/usr/local/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/usr/local/lib/python3.10/site-packages/web3/tools/pytest_ethereum/deployer.py", line 7, in <module>
    from eth_typing import (
ImportError: cannot import name 'ContractName' from 'eth_typing' (/usr/local/lib/python3.10/site-packages/eth_typing/__init__.py)
```

### Fill this section in if you know how this could or should be fixed

Freeze eth_typing to minor version in dependencies

### web3 Version

6.10.0

### Python Version

3.10.13

### Operating System

linux

### Output from `pip freeze`

```shell
aiohttp==3.9.4
aiosignal==1.3.1
annotated-types==0.6.0
async-timeout==4.0.3
attrs==23.2.0
bitarray==2.9.2
certifi==2024.2.2
charset-normalizer==3.3.2
ckzg==1.0.0
cytoolz==0.12.3
eth-account==0.12.2
eth-hash==0.7.0
eth-keyfile==0.8.0
eth-keys==0.5.0
eth-rlp==2.1.0
eth-typing==4.2.0
eth-utils==4.1.0
eth_abi==5.1.0
exceptiongroup==1.2.0
frozenlist==1.4.1
hexbytes==1.2.0
idna==3.7
iniconfig==2.0.0
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
lru-dict==1.3.0
multidict==6.0.5
packaging==24.0
parsimonious==0.10.0
pluggy==1.4.0
protobuf==5.26.1
pycryptodome==3.20.0
pydantic==2.7.0
pydantic_core==2.18.1
pytest==8.1.1
pyunormalize==15.1.0
referencing==0.34.0
regex==2023.12.25
requests==2.31.0
rlp==4.0.0
rpds-py==0.18.0
tomli==2.0.1
toolz==0.12.1
typing_extensions==4.11.0
urllib3==2.2.1
web3==6.10.0
websockets==12.0
yarl==1.9.4
```

**Comment by reedsa** [comment]
We have a patch to fix this issue and will be released first thing tomorrow.

Until then, please continue to use the pin you mentioned.

**Comment by reedsa** [comment]
This should be fixed in https://github.com/ethereum/web3.py/tree/v6.17.2

Apologies for this issue, `eth-typing` v4.2.0 is not a usable release, this was patched and marked as excluded by web3.py.

**Comment by dpaiton** [comment]
FYI @reedsa this seems to have returned. We're seeing the same problem in our CI:

```py
  File "/home/runner/work/agent0/agent0/.venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 174, in exec_module
    exec(co, module.__dict__)
  File "/home/runner/work/agent0/agent0/.venv/lib/python3.10/site-packages/web3/tools/__init__.py", line 1, in <module>
    from .pytest_ethereum import (
  File "/home/runner/work/agent0/agent0/.venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 174, in exec_module
    exec(co, module.__dict__)
  File "/home/runner/work/agent0/agent0/.venv/lib/python3.10/site-packages/web3/tools/pytest_ethereum/deployer.py", line 7, in <module>
    from eth_typing import (
ImportError: cannot import name 'ContractName' from 'eth_typing' 
```

**Comment by dpaiton** [comment]
FYI @reedsa this seems to be still happening (or has returned). 

```
  File "/Users/dylan/code/.venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1377, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/Users/dylan/code/.venv/lib/python3.10/site-packages/pluggy/_manager.py", line 421, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/Users/dylan/.pyenv/versions/3.10.13/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/Users/dylan/.pyenv/versions/3.10.13/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/dylan/code/.venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 174, in exec_module
    exec(co, module.__dict__)
  File "/Users/dylan/code/.venv/lib/python3.10/site-packages/web3/tools/__init__.py", line 1, in <module>
    from .pytest_ethereum import (
  File "/Users/dylan/code/.venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 174, in exec_module
    exec(co, module.__dict__)
  File "/Users/dylan/code/.venv/lib/python3.10/site-packages/web3/tools/pytest_ethereum/deployer.py", line 7, in <module>
    from eth_typing import (
ImportError: cannot import name 'ContractName' from 'eth_typing' (/Users/dylan/code/.venv/lib/python3.10/site-packages/eth_typing/__init__.py)
```

Here are the packages I have installed:
```
Package                       Version           Editable project location
----------------------------- ----------------- -------------------------------------
agent0                        0.21.10           /Users/dylan/code/agent0
aiohappyeyeballs              2.3.5
aiohttp                       3.10.3
aiosignal                     1.3.1
alabaster                     0.7.16
altair                        5.4.0
appnope                       0.1.4
astroid                       3.2.4
asttokens                     2.4.1
async-timeout                 4.0.3
attrs                         24.2.0
autodocsumm                   0.2.13
autoflake                     2.3.1
babel                         2.16.0
backports.tarfile             1.2.0
beautifulsoup4                4.12.3
bitarray                      2.9.2
black                         24.8.0
bleach                        6.1.0
blinker                       1.8.2
build                         1.2.1
cachetools                    5.4.0
certifi                       2024.7.4
charset-normalizer            3.3.2
ckzg                          1.0.2
click                         8.1.7
cloudpickle                   3.0.0
comm                          0.2.2
contourpy                     1.2.1
coverage                      7.6.1
cycler                        0.12.1
cytoolz                       0.12.3
debugpy                       1.8.5
decorator                     5.1.1
defusedxml                    0.7.1
dill                          0.3.8
dm-tree                       0.1.8
docker                        7.1.0
docutils                      0.20.1
eth_abi                       5.1.0
eth-account                   0.11.2
eth-hash                      0.7.0
eth-keyfile                   0.8.1
eth-keys                      0.5.1
eth-rlp                       1.0.1
eth-typing                    5.0.0
eth-utils                     4.1.1
exceptiongroup                1.2.2
executing                     2.0.1
factory-boy                   3.3.0
Faker                         27.0.0
Farama-Notifications          0.0.4
fastjsonschema                2.20.0
filelock                      3.15.4
fixedpointmath                0.2.1             /Users/dylan/code/fixedpointmath
Flask                         3.0.3
flask-expects-json            1.7.0
flit                          3.9.0
flit_core                     3.9.0
fonttools                     4.53.1
frozenlist                    1.4.1
fsspec                        2024.6.1
gitdb                         4.0.11
GitPython                     3.1.43
gymnasium                     0.28.1
hexbytes                      0.3.1
idna                          3.7
imageio                       2.35.0
imagesize                     1.4.1
importlib_metadata            8.2.0
iniconfig                     2.0.0
ipykernel                     6.29.5
ipython                       8.26.0
isort                         5.13.2
itsdangerous                  2.2.0
jaraco.classes                3.4.0
jaraco.context                5.3.0
jaraco.functools              4.0.2
jax-jumpy                     1.0.0
jedi                          0.19.1
Jinja2                        3.1.4
jsonschema                    4.23.0
jsonschema-specifications     2023.12.1
jupyter_client                8.6.2
jupyter_core                  5.7.2
jupyterlab_pygments           0.3.0
jupytext                      1.16.4
keyring                       25.3.0
kiwisolver                    1.4.5
lazy_loader                   0.4
lru-dict                      1.2.0
lz4                           4.3.3
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
matplotlib                    3.9.2
matplotlib-inline             0.1.7
mccabe                        0.7.0
mdit-py-plugins               0.4.1
mdurl                         0.1.2
mirakuru                      2.5.2
mistune                       3.0.2
more-itertools                10.4.0
mplfinance                    0.12.10b0
mpmath                        1.3.0
msgpack                       1.0.8
multidict                     6.0.5
mypy-extensions               1.0.0
myst-parser                   4.0.0
narwhals                      1.4.1
nbclient                      0.10.0
nbconvert                     7.16.4
nbformat                      5.10.4
nbsphinx                      0.9.5
nest-asyncio                  1.6.0
networkx                      3.3
nh3                           0.2.18
nodeenv                       1.9.1
numpy                         1.26.4
numpydoc                      1.8.0
packaging                     24.1
pandas                        2.2.2
pandas-stubs                  2.2.2.240807
pandocfilters                 1.5.1
parsimonious                  0.10.0
parso                         0.8.4
pathspec                      0.12.1
pexpect                       4.9.0
pillow                        10.4.0
pip                           24.2
pkginfo                       1.10.0
platformdirs                  4.2.2
pluggy                        1.5.0
pockets                       0.9.1
port-for                      0.7.2
prompt_toolkit                3.0.47
protobuf                      5.27.3
psutil                        6.0.0
psycopg                       3.2.1
psycopg-binary                3.2.1
ptyprocess                    0.7.0
pure_eval                     0.2.3
pyarrow                       17.0.0
pycryptodome                  3.20.0
pydeck                        0.9.1
pyflakes                      3.2.0
Pygments                      2.18.0
pylint                        3.2.6
pyparsing                     3.1.2
pypechain                     0.0.32
pyproject_hooks               1.1.0
pyright                       1.1.376
pytest                        8.3.2
pytest-postgresql             6.0.1
pytest-snapshot               0.9.0
python-dateutil               2.9.0.post0
python-dotenv                 1.0.1
pytz                          2024.1
pyunormalize                  15.1.0
PyYAML                        6.0.2
pyzmq                         26.1.0
ray                           2.34.0
readme_renderer               43.0
referencing                   0.35.1
regex                         2024.7.24
requests                      2.32.3
requests-toolbelt             1.0.0
rfc3986                       2.0.0
rich                          13.7.1
rlp                           4.0.1
rollbar                       1.0.0
rpds-py                       0.20.0
scikit-image                  0.24.0
scipy                         1.14.0
setuptools                    72.2.0
shellingham                   1.5.4
six                           1.16.0
smmap                         5.0.1
snowballstemmer               2.2.0
soupsieve                     2.6
Sphinx                        7.4.7
sphinx-autoapi                3.2.1
sphinx-autodoc-typehints      2.2.3
sphinx-rtd-theme              2.0.0
sphinxcontrib-applehelp       2.0.0
sphinxcontrib-devhelp         2.0.0
sphinxcontrib-htmlhelp        2.1.0
sphinxcontrib-jquery          4.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-napoleon        0.7
sphinxcontrib-qthelp          2.0.0
sphinxcontrib-serializinghtml 2.0.0
SQLAlchemy                    2.0.32
SQLAlchemy-Utils              0.41.2
stable_baselines3             2.3.2
stack-data                    0.6.3
streamlit                     1.37.1
sympy                         1.13.2
tabulate                      0.9.0
tenacity                      8.5.0
tensorboardX                  2.6.2.2
tifffile                      2024.8.10
tinycss2                      1.3.0
toml                          0.10.2
tomli                         2.0.1
tomli_w                       1.0.0
tomlkit                       0.13.2
toolz                         0.12.1
torch                         2.4.0
tornado                       6.4.1
tqdm                          4.66.5
traitlets                     5.14.3
twine                         5.1.1
typer                         0.12.3
types-pytz                    2024.1.0.20240417
typing_extensions             4.12.2
tzdata                        2024.1
urllib3                       2.2.2
wcwidth                       0.2.13
web3                          6.20.1
webencodings                  0.5.1
websockets                    12.0
Werkzeug                      3.0.3
wheel                         0.44.0
yarl                          1.9.4
zipp                          3.20.0
```

Of note are `web3==6.20.1` and `eth-typing==5.0.0`, which was released 2 hours ago. So I'm guessing y'all have to set this latest `eth-typing` as incompatible as well? I also commented here: https://github.com/ethereum/eth-typing/issues/63

**Comment by kclowes** [comment]
@dpaiton thanks for the heads up. We're working on a fix right now, but you can workaround by requiring `eth-typing>3,<5, !=4.2.0` in your local environment

**Comment by mpeyfuss** [comment]
`eth_typing` also has to be less than 5.0.0 because of this same issue

**Comment by kclowes** [comment]
Patch released in web3.py `v6.20.2`. Sorry for the inconvenience!

**Comment by mpeyfuss** [comment]
Thanks!
